In [1]:
import numpy as np

In [22]:
X = np.array([500, 700, 750, 600, 1450, 800, 1500, 2000, 450, 1000])

In [31]:
def standart_X(X):
    _mean = X.mean()
    _std = (np.sum((X-_mean)**2)/len(X))**0.5
    standart_X = (X-_mean)/_std
    return standart_X

In [24]:
def min_max_X(X):
    _max = X.max()
    _min = X.min()
    min_max_X = (X-_min)/(_max-_min)
    return min_max_X

In [32]:
_standart_X = standart_X(X.copy())
_standart_X

array([-0.97958969, -0.56713087, -0.46401617, -0.77336028,  0.97958969,
       -0.36090146,  1.08270439,  2.11385144, -1.08270439,  0.05155735])

In [26]:
_min_max_X = min_max_X(X.copy())
_min_max_X

array([0.03225806, 0.16129032, 0.19354839, 0.09677419, 0.64516129,
       0.22580645, 0.67741935, 1.        , 0.        , 0.35483871])

In [27]:
_standart_min_max_X = standart_X(_min_max_X)
_standart_min_max_X

array([-0.97958969, -0.56713087, -0.46401617, -0.77336028,  0.97958969,
       -0.36090146,  1.08270439,  2.11385144, -1.08270439,  0.05155735])

In [28]:
_min_max_standart_X = min_max_X(_standart_X)
_min_max_standart_X

array([0.03225806, 0.16129032, 0.19354839, 0.09677419, 0.64516129,
       0.22580645, 0.67741935, 1.        , 0.        , 0.35483871])